# Generated by Django 5.2.12 on 2026-03-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload the video file (mp4 recommended).', null=True, upload_to='topics/videos/'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='video_url',
            field=models.URLField(blank=True, help_text='OR paste an external video URL (YouTube embed, etc.)'),
        ),
    ]
