# Generated by Django 6.0.3 on 2026-03-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='predefined_quiz',
            field=models.JSONField(blank=True, help_text='AI-generated fallback quiz questions.', null=True),
        ),
    ]
