# Generated by Django 6.0.3 on 2026-03-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, default='', help_text='Short bio (max 120 chars)', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status_emoji',
            field=models.CharField(blank=True, choices=[('🚀', 'Coding'), ('📚', 'Studying'), ('🏆', 'Competing'), ('💡', 'Building'), ('💤', 'AFK')], default='🚀', max_length=4),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
