# Generated by Django 6.0.3 on 2026-03-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_bio_userprofile_status_emoji_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', help_text='Link to your LinkedIn profile', max_length=255),
        ),
    ]
